TERM = "alacritty"
dynamic_title = true
hide_when_typing = true

[font]
size = 22.0

[font.bold]
style = "Semibold"

[font.bold_italic]
style = "Semibold Italic"

[font.italic]
style = "Light Italic"

[font.normal]
family = "SauceCodePro Nerd Font Mono"
style = "Light"

[window]
opacity = 0.75
startup_mode = "Maximized"
